### ISSUE TITLE
[feature/comment-service] 댓글 CRUD

### ISSUE THREAD

**Issue by dldmsql** [ODOICHON/server#12]
## Notice 
댓글 작성, 조회, 수정, 삭제 API 기능 개발

## Task
- [x] Comment 도메인 정의
- [x] API 기능 개발
- [x] 포스트맨 확인
- [x] 테스트 코드 작성

**Comment by dldmsql** [comment]
react-quill 라이브러리를 통해 code 데이터가 HTML 형태로 넘어오는 것에 따른 DB 조작 필요.

1. MySQL 서버에 admin 계정으로 접속
2. 아래 함수 쿼리 실행
 ```` bash
CREATE FUNCTION `strip_tags`($str text) RETURNS text
BEGIN
    DECLARE $start, $end INT DEFAULT 1;
LOOP
    SET $start = LOCATE('<', $str, $start);
    IF (!$start) THEN RETURN $str; END IF;
    SET $end = LOCATE('>', $str, $start);
    IF (!$end) THEN SET $end = $start; END IF;
    SET $str = INSERT($str, $start, $end - $start + 1, "");
END LOOP;
END;
````

만약 오류 발생 시, MySQL 서버 자체에 함수 생성 옵션이 OFF인지 확인하기.

```` bash
show global variables like 'log_bin_trust_function_creators';
SET GLOBAL log_bin_trust_function_creators = 1;
````

3. 조회 쿼리 조건으로 strip_tags() 사용

참고 레퍼런스

[스택오버플로우](https://stackoverflow.com/questions/18040097/mysql-extract-plaintext-from-html-data-or-php)

[mysql 함수 생성 오류](https://myhappyman.tistory.com/154)
