### ISSUE TITLE
[feat/back-office] 백오피스 개발

### ISSUE THREAD

**Issue by MoonMinHyuk1** [ODOICHON/server#143]
## 주요 작업 내용
> 백오피스 페이지 api 개발

## To-Do

- [x] Autority 타입 추가(SERVER, WEB)
- [x] 사용자 테이블 대표 이미지 url 컬럼 추가
- [x] 도메인 설계 & 연관관계 매핑
- [x] 게시글 api 개발
- [x] 템플릿 api 개발
- [x] 리뷰 api 개발
- [x] 댓글 api 개발
