### ISSUE TITLE
[feat/house-service] 빈집 거래 서비스 개발

### ISSUE THREAD

**Issue by dldmsql** [ODOICHON/server#171]
## 주요 작업 내용
> 한 줄로 정리해주세요.

빈집 거래 서비스 개발을 진행합니다.

## To-Do

- [x] 빈집 거래 관련 ERD 설계
- [x] 빈집 게시글 API 구현
- [x] 테스트 코드 작성

## Notice
> 전달 사항을 작성하거나 위키 페이지 링크를 걸어주세요.
