### ISSUE TITLE
[fix/house-service] 빈집 게시글 API 추가 개발

### ISSUE THREAD

**Issue by dldmsql** [ODOICHON/server#187]
## 주요 작업 내용
> 한 줄로 정리해주세요.

빈집 게시글 API 추가 개발 및 수정

## To-Do

- [x] 빈집 게시글 임시저장 -> 마이페이지에서 조회
- [x] 빈집 게시글 스크랩 -> 마이페이지에서 조회
- [x] 빈집 게시글 조회 조건 수정 ( 임시저장, 승인여부, 삭제여부 ) false, true, false 일 때 노출
- [x] 빈집 게시글 승인여부 ( 일반 유저에 한해서 ) -> 승인 처리는 관라자페이지에서
- [x] 빈집 게시글 2차 캐싱 도입

## Notice
> 전달 사항을 작성하거나 위키 페이지 링크를 걸어주세요.

**Comment by dldmsql** [comment]
[2차캐싱](https://www.inflearn.com/questions/33629/%EA%B0%95%EC%9D%98%EC%97%90%EB%8A%94-%EC%97%86%EB%8A%94-%EB%82%B4%EC%9A%A9%EC%9D%B4%EC%A7%80%EB%A7%8C-cache-%EA%B4%80%EB%A0%A8%ED%95%B4%EC%84%9C-%EC%A7%88%EB%AC%B8%EC%9D%B4-%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4)

**Comment by dldmsql** [comment]
[캐싱정리](https://jaehun2841.github.io/2018/11/07/2018-10-03-spring-ehcache/#EHCache-%EC%98%88%EC%8B%9C-%EC%BD%94%EB%93%9C)
