### ISSUE TITLE
[feat/user-service] 회원가입 시, 약관 동의 여부 데이터 디비 저장

### ISSUE THREAD

**Issue by dldmsql** [ODOICHON/server#237]
## 주요 작업 내용
> 한 줄로 정리해주세요.

회원가입 시, 약관 동의 여부 데이터 디비 저장

## To-Do

- [x] user_join_path와 같이 user와 비식별관계인 user_terms 테이블 생성
- [x] 회원가입 로직 수정
- [x] 회원가입 테스트 코드 수정
- [x] API 문서화 작업

## Notice
> 전달 사항을 작성하거나 위키 페이지 링크를 걸어주세요.
