### ISSUE TITLE
[feature/user-service] 이메일 인증 구현

### ISSUE THREAD

**Issue by dldmsql** [ODOICHON/server#247]
## To-Do

- [x] 이메일 인증코드 전송 API 개발
- [x] 이메일 인증코드 검증 API 개발
- [x] 테스트코드 작성
- [x] 문서화
- [x] 이메일 인증 실패 이력 관리

## Notice
> 전달 사항을 작성하거나 위키 페이지 링크를 걸어주세요.
